
package webservices.modelo2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "FuncionarioModelo2WsService", targetNamespace = "http://services.soc.age.com/", wsdlLocation = "https://ws1.soc.com.br/WSSoc/FuncionarioModelo2Ws?wsdl")
public class FuncionarioModelo2WsService
    extends Service
{

    private final static URL FUNCIONARIOMODELO2WSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservices.modelo2.FuncionarioModelo2WsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservices.modelo2.FuncionarioModelo2WsService.class.getResource(".");
            url = new URL(baseUrl, "https://www.p-soc.com.br/WSSoc/FuncionarioModelo2Ws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.p-soc.com.br/WSSoc/FuncionarioModelo2Ws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FUNCIONARIOMODELO2WSSERVICE_WSDL_LOCATION = url;
    }

    public FuncionarioModelo2WsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FuncionarioModelo2WsService() {
        super(FUNCIONARIOMODELO2WSSERVICE_WSDL_LOCATION, new QName("http://services.soc.age.com/", "FuncionarioModelo2WsService"));
    }

    /**
     * 
     * @return
     *     returns FuncionarioModelo2Ws
     */
    @WebEndpoint(name = "FuncionarioModelo2WsPort")
    public FuncionarioModelo2Ws getFuncionarioModelo2WsPort() {
        return super.getPort(new QName("http://services.soc.age.com/", "FuncionarioModelo2WsPort"), FuncionarioModelo2Ws.class);
    }

}
