
package webservices.exportadados;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ExportaDadosWs", targetNamespace = "http://services.soc.age.com/")
public interface ExportaDadosWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.exportadados.ExportaDadosWsVo
     * @throws WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exportaDadosWs", targetNamespace = "http://services.soc.age.com/", className = "webservices.exportadados.ExportaDadosWs_Type")
    @ResponseWrapper(localName = "exportaDadosWsResponse", targetNamespace = "http://services.soc.age.com/", className = "webservices.exportadados.ExportaDadosWsResponse")
    public ExportaDadosWsVo exportaDadosWs(
        @WebParam(name = "arg0", targetNamespace = "")
        ExportaDadosWsVo arg0)
        throws WSException_Exception
    ;

}
