
package webservices.exportadados;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ExportaDadosWsService", targetNamespace = "http://services.soc.age.com/", wsdlLocation = "https://ws1.soc.com.br/WSSoc/services/ExportaDadosWs?wsdl")
public class ExportaDadosWsService
    extends Service
{

    private final static URL EXPORTADADOSWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservices.exportadados.ExportaDadosWsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservices.exportadados.ExportaDadosWsService.class.getResource(".");
            url = new URL(baseUrl, "https://www.p-soc.com.br/WSSoc/services/ExportaDadosWs?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://ws1.soc.com.br/WSSoc/services/ExportaDadosWs?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EXPORTADADOSWSSERVICE_WSDL_LOCATION = url;
    }

    public ExportaDadosWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExportaDadosWsService() {
        super(EXPORTADADOSWSSERVICE_WSDL_LOCATION, new QName("http://services.soc.age.com/", "ExportaDadosWsService"));
    }

    /**
     * 
     * @return
     *     returns ExportaDadosWs
     */
    @WebEndpoint(name = "ExportaDadosWsPort")
    public ExportaDadosWs getExportaDadosWsPort() {
        return super.getPort(new QName("http://services.soc.age.com/", "ExportaDadosWsPort"), ExportaDadosWs.class);
    }

}
