
package webservices.exportadados;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "WSException", targetNamespace = "http://services.soc.age.com/")
public class WSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WSException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WSException_Exception(String message, WSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WSException_Exception(String message, WSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.exportadados.WSException
     */
    public WSException getFaultInfo() {
        return faultInfo;
    }

}
