
package webservices.uploadArquivos;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "UploadArquivosWsService", targetNamespace = "http://services.soc.age.com/", wsdlLocation = "https://ws1.soc.com.br/WSSoc/services/UploadArquivosWs?wsdl")
public class UploadArquivosWsService
    extends Service
{

    private final static URL UPLOADARQUIVOSWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservices.uploadArquivos.UploadArquivosWsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservices.uploadArquivos.UploadArquivosWsService.class.getResource(".");
            url = new URL(baseUrl, "https://www.p-soc.com.br/WSSoc/services/UploadArquivosWs?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://ws1.soc.com.br/WSSoc/services/UploadArquivosWs?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        UPLOADARQUIVOSWSSERVICE_WSDL_LOCATION = url;
    }

    public UploadArquivosWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadArquivosWsService() {
        super(UPLOADARQUIVOSWSSERVICE_WSDL_LOCATION, new QName("http://services.soc.age.com/", "UploadArquivosWsService"));
    }

    /**
     * 
     * @return
     *     returns UploadArquivosWs
     */
    @WebEndpoint(name = "UploadArquivosWsPort")
    public UploadArquivosWs getUploadArquivosWsPort() {
        return super.getPort(new QName("http://services.soc.age.com/", "UploadArquivosWsPort"), UploadArquivosWs.class);
    }

}
