
package webservices.uploadArquivos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UploadArquivosWs", targetNamespace = "http://services.soc.age.com/")
public interface UploadArquivosWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws WSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadArquivo", targetNamespace = "http://services.soc.age.com/", className = "webservices.uploadArquivos.UploadArquivo")
    @ResponseWrapper(localName = "uploadArquivoResponse", targetNamespace = "http://services.soc.age.com/", className = "webservices.uploadArquivos.UploadArquivoResponse")
    public boolean uploadArquivo(
        @WebParam(name = "arg0", targetNamespace = "")
        UploadArquivosWsVo arg0)
        throws WSException_Exception
    ;

    /**
     * 
     * @param socged
     * @return
     *     returns webservices.uploadArquivos.GedWsRetornoVo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateGed", targetNamespace = "http://services.soc.age.com/", className = "webservices.uploadArquivos.UpdateGed")
    @ResponseWrapper(localName = "updateGedResponse", targetNamespace = "http://services.soc.age.com/", className = "webservices.uploadArquivos.UpdateGedResponse")
    public GedWsRetornoVo updateGed(
        @WebParam(name = "socged", targetNamespace = "")
        WebServiceGedVo socged);

}
